### ISSUE TITLE
This is great, but I get issues with numpy

### ISSUE THREAD

**Issue by biofects** [artibex/piper-http#2]
I tested your build and it worked, however I wanted to build my own and set the voices. 
```Folder path = /app/models
Downloaded https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx.json to /app/models/model.onnx.json

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/app/piper/src/python_run/piper/__init__.py", line 1, in <module>
    from .voice import PiperVoice
  File "/app/piper/src/python_run/piper/voice.py", line 9, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.11/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/local/lib/python3.11/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/app/piper/src/python_run/piper/__init__.py", line 1, in <module>
    from .voice import PiperVoice
  File "/app/piper/src/python_run/piper/voice.py", line 9, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.11/site-packages/onnxruntime/__init__.py", line 57, in <module>
    raise import_capi_exception
  File "/usr/local/lib/python3.11/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError```

I hope you can see where my error is. I cannot even build with a direct download

**Comment by artibex** [comment]
`A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x`

My guess is that your numby version is too new for this to build but I have no time to look into it sadly. Using the english voice example also leads to this error?

**Comment by artibex** [comment]
I'm closing the issue because no response was given.

If other people have this issue, please install a seperate Anaconda python environment with the requirements.txt file provided by the offocial piper github repo to fix dependency issues
